const emojipedia = [
  {
    id: 1,
    emoji: "😀",
    name: "Grinning Face",
    meaning: "General happiness and friendliness.",
  },
  {
    id: 2,
    emoji: "😂",
    name: "Face With Tears of Joy",
    meaning: "Something is extremely funny.",
  },
  {
    id: 3,
    emoji: "🤣",
    name: "Rolling on the Floor Laughing",
    meaning: "Uncontrollable laughter.",
  },
  {
    id: 4,
    emoji: "😅",
    name: "Grinning Face with Sweat",
    meaning: "Relief or awkwardness.",
  },
  {
    id: 5,
    emoji: "😊",
    name: "Smiling Face with Smiling Eyes",
    meaning: "Warmth, happiness.",
  },
  {
    id: 6,
    emoji: "😍",
    name: "Smiling Face with Heart-Eyes",
    meaning: "Love or admiration.",
  },
  {
    id: 7,
    emoji: "😘",
    name: "Face Blowing a Kiss",
    meaning: "Affection, love.",
  },
  {
    id: 8,
    emoji: "😎",
    name: "Smiling Face with Sunglasses",
    meaning: "Coolness, confidence.",
  },
  { id: 9, emoji: "😢", name: "Crying Face", meaning: "Sadness or pain." },
  {
    id: 10,
    emoji: "😭",
    name: "Loudly Crying Face",
    meaning: "Extreme sadness or laughter.",
  },
  { id: 11, emoji: "😡", name: "Pouting Face", meaning: "Anger, frustration." },
  {
    id: 12,
    emoji: "🤯",
    name: "Exploding Head",
    meaning: "Mind-blown reaction.",
  },
  {
    id: 13,
    emoji: "🥳",
    name: "Partying Face",
    meaning: "Celebration, party mood.",
  },
  {
    id: 14,
    emoji: "🤔",
    name: "Thinking Face",
    meaning: "Deep thought, questioning.",
  },
  {
    id: 15,
    emoji: "🙄",
    name: "Face with Rolling Eyes",
    meaning: "Sarcasm, annoyance.",
  },
  { id: 16, emoji: "😴", name: "Sleeping Face", meaning: "Tired, bored." },
  {
    id: 17,
    emoji: "🤤",
    name: "Drooling Face",
    meaning: "Delicious food or desire.",
  },
  {
    id: 18,
    emoji: "😇",
    name: "Smiling Face with Halo",
    meaning: "Innocence or good deed.",
  },
  {
    id: 19,
    emoji: "🤡",
    name: "Clown Face",
    meaning: "Silliness or foolishness.",
  },
  {
    id: 20,
    emoji: "💩",
    name: "Pile of Poo",
    meaning: "Humor, silliness, or frustration.",
  },
  { id: 21, emoji: "👋", name: "Waving Hand", meaning: "Hello or goodbye." },
  {
    id: 22,
    emoji: "🤚",
    name: "Raised Back of Hand",
    meaning: "Stop or high-five.",
  },
  {
    id: 23,
    emoji: "👏",
    name: "Clapping Hands",
    meaning: "Applause or appreciation.",
  },
  {
    id: 24,
    emoji: "🙌",
    name: "Raising Hands",
    meaning: "Celebration, praise.",
  },
  {
    id: 25,
    emoji: "🙏",
    name: "Folded Hands",
    meaning: "Prayer, thanks, or high-five.",
  },
  {
    id: 26,
    emoji: "🤝",
    name: "Handshake",
    meaning: "Agreement or partnership.",
  },
  { id: 27, emoji: "👍", name: "Thumbs Up", meaning: "Approval or agreement." },
  { id: 28, emoji: "👎", name: "Thumbs Down", meaning: "Disapproval." },
  { id: 29, emoji: "✌️", name: "Victory Hand", meaning: "Peace or victory." },
  {
    id: 30,
    emoji: "🤞",
    name: "Crossed Fingers",
    meaning: "Hoping for good luck.",
  },
  {
    id: 31,
    emoji: "🤟",
    name: "Love-You Gesture",
    meaning: "Friendly or loving gesture.",
  },
  { id: 32, emoji: "👌", name: "OK Hand", meaning: "Perfection, agreement." },
  {
    id: 33,
    emoji: "💪",
    name: "Flexed Biceps",
    meaning: "Strength or encouragement.",
  },
  {
    id: 34,
    emoji: "👀",
    name: "Eyes",
    meaning: "Watching, attention, or surprise.",
  },
  { id: 35, emoji: "👑", name: "Crown", meaning: "Royalty, power." },
  { id: 36, emoji: "💋", name: "Kiss Mark", meaning: "Romance, affection." },
  { id: 37, emoji: "❤️", name: "Red Heart", meaning: "Love, affection." },
  {
    id: 38,
    emoji: "🧡",
    name: "Orange Heart",
    meaning: "Friendship or warmth.",
  },
  {
    id: 39,
    emoji: "💛",
    name: "Yellow Heart",
    meaning: "Happiness, friendship.",
  },
  { id: 40, emoji: "💚", name: "Green Heart", meaning: "Jealousy or health." },
  {
    id: 41,
    emoji: "💙",
    name: "Blue Heart",
    meaning: "Trust, peace, loyalty.",
  },
  { id: 42, emoji: "💜", name: "Purple Heart", meaning: "Compassion, love." },
  { id: 43, emoji: "🖤", name: "Black Heart", meaning: "Dark humor, sorrow." },
  {
    id: 44,
    emoji: "💔",
    name: "Broken Heart",
    meaning: "Heartbreak or sadness.",
  },
  { id: 45, emoji: "💕", name: "Two Hearts", meaning: "Romance or affection." },
  {
    id: 46,
    emoji: "❣️",
    name: "Heart Exclamation",
    meaning: "Excitement, love.",
  },
  { id: 47, emoji: "💞", name: "Revolving Hearts", meaning: "Mutual love." },
  { id: 48, emoji: "💓", name: "Beating Heart", meaning: "Love, affection." },
  {
    id: 49,
    emoji: "💗",
    name: "Growing Heart",
    meaning: "Expanding affection.",
  },
  { id: 50, emoji: "💖", name: "Sparkling Heart", meaning: "Excited love." },
  { id: 51, emoji: "💘", name: "Heart with Arrow", meaning: "Love struck." },
  { id: 52, emoji: "💝", name: "Heart with Ribbon", meaning: "Gift of love." },
  { id: 53, emoji: "🔥", name: "Fire", meaning: "Hot, lit, amazing." },
  { id: 54, emoji: "✨", name: "Sparkles", meaning: "Magic, beauty." },
  {
    id: 55,
    emoji: "🌟",
    name: "Glowing Star",
    meaning: "Special or outstanding.",
  },
  { id: 56, emoji: "⭐", name: "Star", meaning: "Fame, success." },
  { id: 57, emoji: "⚡", name: "High Voltage", meaning: "Power, shock." },
  { id: 58, emoji: "☀️", name: "Sun", meaning: "Bright, happy." },
  { id: 59, emoji: "🌙", name: "Crescent Moon", meaning: "Night, calm." },
  { id: 60, emoji: "🌈", name: "Rainbow", meaning: "Happiness, diversity." },
  { id: 61, emoji: "☁️", name: "Cloud", meaning: "Weather or mood." },
  { id: 62, emoji: "❄️", name: "Snowflake", meaning: "Cold, unique." },
  { id: 63, emoji: "💧", name: "Droplet", meaning: "Water, sweat, or tears." },
  {
    id: 64,
    emoji: "🌍",
    name: "Globe Europe-Africa",
    meaning: "Earth, global.",
  },
  { id: 65, emoji: "🌸", name: "Cherry Blossom", meaning: "Spring, beauty." },
  { id: 66, emoji: "🌹", name: "Rose", meaning: "Romance, beauty." },
  { id: 67, emoji: "🍀", name: "Four Leaf Clover", meaning: "Luck." },
  { id: 68, emoji: "🐶", name: "Dog Face", meaning: "Pets, loyalty." },
  { id: 69, emoji: "🐱", name: "Cat Face", meaning: "Cuteness, pets." },
  { id: 70, emoji: "🐻", name: "Bear Face", meaning: "Cuddly, strength." },
  { id: 71, emoji: "🐼", name: "Panda Face", meaning: "Cute, conservation." },
  { id: 72, emoji: "🐵", name: "Monkey Face", meaning: "Playfulness." },
  {
    id: 73,
    emoji: "🙈",
    name: "See-No-Evil Monkey",
    meaning: "Avoiding or shyness.",
  },
  {
    id: 74,
    emoji: "🙉",
    name: "Hear-No-Evil Monkey",
    meaning: "Ignoring noise.",
  },
  {
    id: 75,
    emoji: "🙊",
    name: "Speak-No-Evil Monkey",
    meaning: "Keeping quiet.",
  },
  { id: 76, emoji: "🐔", name: "Chicken", meaning: "Farm animal, cowardice." },
  { id: 77, emoji: "🐤", name: "Baby Chick", meaning: "Cuteness, youth." },
  { id: 78, emoji: "🐧", name: "Penguin", meaning: "Cold places, cuteness." },
  { id: 79, emoji: "🐢", name: "Turtle", meaning: "Slowness, patience." },
  {
    id: 80,
    emoji: "🐠",
    name: "Tropical Fish",
    meaning: "Sea life, aquariums.",
  },
  { id: 81, emoji: "🐙", name: "Octopus", meaning: "Sea creature, versatile." },
  {
    id: 82,
    emoji: "🍎",
    name: "Red Apple",
    meaning: "Health, teacher, temptation.",
  },
  { id: 83, emoji: "🍌", name: "Banana", meaning: "Fruit, silliness." },
  { id: 84, emoji: "🍉", name: "Watermelon", meaning: "Summer, refreshment." },
  { id: 85, emoji: "🍇", name: "Grapes", meaning: "Fruit, abundance." },
  { id: 86, emoji: "🍓", name: "Strawberry", meaning: "Sweetness, summer." },
  { id: 87, emoji: "🍒", name: "Cherries", meaning: "Playful, cute." },
  { id: 88, emoji: "🍍", name: "Pineapple", meaning: "Tropical, hospitality." },
  { id: 89, emoji: "🥭", name: "Mango", meaning: "Tropical fruit, sweetness." },
  { id: 90, emoji: "🍕", name: "Pizza", meaning: "Food cravings, parties." },
  { id: 91, emoji: "🍔", name: "Burger", meaning: "Fast food, casual eating." },
  {
    id: 92,
    emoji: "🍟",
    name: "French Fries",
    meaning: "Snacking, fast food.",
  },
  { id: 93, emoji: "🌭", name: "Hot Dog", meaning: "Fast food, street food." },
  { id: 94, emoji: "🍩", name: "Doughnut", meaning: "Sweet treat." },
  { id: 95, emoji: "🍪", name: "Cookie", meaning: "Snack, sweetness." },
  { id: 96, emoji: "🍫", name: "Chocolate Bar", meaning: "Sweet, indulgence." },
  { id: 97, emoji: "🍿", name: "Popcorn", meaning: "Movies, fun." },
  { id: 98, emoji: "🍺", name: "Beer Mug", meaning: "Drinking, celebration." },
  { id: 99, emoji: "🍷", name: "Wine Glass", meaning: "Relaxation, elegance." },
  {
    id: 100,
    emoji: "☕",
    name: "Hot Beverage",
    meaning: "Coffee, tea, or morning vibes.",
  },
];

export default emojipedia;
